# RAG Examples Package
# 导出 Milvus 配置供子模块使用

from .milvus_config import MILVUS_URI, DEFAULT_COLLECTION_NAME, DEFAULT_DIMENSION, DEFAULT_METRIC_TYPE

__all__ = ['MILVUS_URI', 'DEFAULT_COLLECTION_NAME', 'DEFAULT_DIMENSION', 'DEFAULT_METRIC_TYPE']
